table Atualização
	lineageTag: 35a60d30-1af2-4f55-836e-0e9dd6bf3c29

	measure 'Última Atualização' = CONCATENATE("Última Atualização: ", SELECTEDVALUE('Atualização'[Atualização]))
		lineageTag: 82c5dc1d-7e2c-44d5-925e-989098becd88

	column Atualização
		dataType: dateTime
		formatString: General Date
		lineageTag: 92e76aae-ee1e-4a03-bde9-ab465fb02e17
		summarizeBy: none
		sourceColumn: Atualização

		variation Variation
			isDefault
			relationship: 1843cc28-f884-4594-9ce4-cef366886045
			defaultHierarchy: LocalDateTable_5647dc8d-bf0c-4aee-a770-5f7092765488.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	partition Atualização-ba830f68-1511-43d2-ad3c-7369121c75d4 = m
		mode: import
		source =
				let
				    Fonte = DateTimeZone.SwitchZone(DateTimeZone.LocalNow(),-3,0),
				    #"Convertido para Tabela" = #table(1, {{Fonte}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Convertido para Tabela",{{"Column1", type datetimezone}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"Column1", "Atualização"}})
				in
				    #"Colunas Renomeadas"

	annotation PBI_ResultType = Table

