table Consulta1
	lineageTag: 3ed3e34a-bb69-4ade-858e-443138fce91f

	column cd_os
		dataType: int64
		formatString: 0
		lineageTag: 44572cbd-8dc1-4a2c-b6a5-3b3f6d50943a
		summarizeBy: sum
		sourceColumn: cd_os

		annotation SummarizationSetBy = Automatic

	column cd_selb
		dataType: string
		lineageTag: 77a0ca21-e06a-42be-8c41-3f8a5304dad0
		summarizeBy: none
		sourceColumn: cd_selb

		annotation SummarizationSetBy = Automatic

	column tipo_os
		dataType: string
		lineageTag: 64812d37-6563-48f4-884a-bc2fd42fdf79
		summarizeBy: none
		sourceColumn: tipo_os

		annotation SummarizationSetBy = Automatic

	column ds_cidade
		dataType: string
		lineageTag: 87350384-c7a6-428a-b0e2-e84f17519745
		summarizeBy: none
		sourceColumn: ds_cidade

		annotation SummarizationSetBy = Automatic

	column ds_uf
		dataType: string
		lineageTag: ad209f86-a481-4c02-9def-f6b2dbf75023
		summarizeBy: none
		sourceColumn: ds_uf

		annotation SummarizationSetBy = Automatic

	column ds_servico
		dataType: string
		lineageTag: f4e975ec-71f9-44b6-a426-8a23094553c3
		summarizeBy: none
		sourceColumn: ds_servico

		annotation SummarizationSetBy = Automatic

	column ds_solucao
		dataType: string
		lineageTag: 1b29cfb1-9d69-43cf-acaf-d81628ff3913
		summarizeBy: none
		sourceColumn: ds_solucao

		annotation SummarizationSetBy = Automatic

	column dt_em_deslocamento
		dataType: dateTime
		formatString: General Date
		lineageTag: 33e9a873-6211-4f46-849d-39eb2c5fb2cb
		summarizeBy: none
		sourceColumn: dt_em_deslocamento

		variation Variation
			isDefault
			relationship: 2f424ed0-1cca-48e0-a7b9-7d9c6ad85ed9
			defaultHierarchy: LocalDateTable_8b8e4d36-0dfb-4dc8-a469-73be1b536e24.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column dt_em_atendimento
		dataType: dateTime
		formatString: General Date
		lineageTag: 57c1d386-4198-4caa-9e36-69ef726de6d5
		summarizeBy: none
		sourceColumn: dt_em_atendimento

		variation Variation
			isDefault
			relationship: e7769239-b0fb-40be-84e1-2d5cd9068c9f
			defaultHierarchy: LocalDateTable_8ff4b3ef-1744-460a-b18d-3a3b300f1898.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column dt_atendimento_concluido
		dataType: dateTime
		formatString: General Date
		lineageTag: 329e9333-c2aa-4755-9307-de276876ce86
		summarizeBy: none
		sourceColumn: dt_atendimento_concluido

		variation Variation
			isDefault
			relationship: a84b8d31-2490-4691-ad9a-8e6607132ccd
			defaultHierarchy: LocalDateTable_000098a5-8911-4a4c-8136-055ce4da9465.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Tempo Em Atendimento'
		dataType: double
		lineageTag: e3788cee-1818-43ac-90be-ac96801c078c
		summarizeBy: sum
		sourceColumn: Tempo Em Atendimento

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Personalizar
		dataType: double
		lineageTag: a8035a4b-55de-46cc-b366-86f98bd4eb21
		summarizeBy: sum
		sourceColumn: Personalizar

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Personalizar.1'
		dataType: string
		lineageTag: b0b1fcc4-892f-45f9-8093-956e3685a2c7
		summarizeBy: none
		sourceColumn: Personalizar.1

		annotation SummarizationSetBy = Automatic

	partition Consulta1 = m
		mode: import
		source =
				let
				    Fonte = Sql.Database("samsung\matriz", "smartmanager", [Query="SELECT#(lf)    ORDEM_SERVICO.cd_os#(lf)    ,ORDEM_SERVICO.cd_selb#(lf)    ,ORDEM_SERVICO.ds_identificacao3                AS tipo_os#(lf)    ,CIDADE.ds_cidade#(lf)    ,UF.ds_uf#(lf)    ,ORDEM_SERVICO.ds_servico#(lf)    ,ORDEM_SERVICO.ds_obs                           AS ds_solucao#(lf)    ,(#(lf)        SELECT TOP 1#(lf)            dt_log_os#(lf)        FROM#(lf)            LOG_OS WITH (NOLOCK)#(lf)#(lf)        WHERE #(lf)            LOG_OS.vl_os = ORDEM_SERVICO.cd_os#(lf)            AND LOG_OS.cd_status = 29 #(lf)        ORDER BY#(lf)            LOG_OS.dt_log_os DESC#(lf)    )                                               AS dt_em_deslocamento#(lf)    ,(#(lf)        SELECT TOP 1#(lf)            dt_log_os#(lf)        FROM#(lf)            LOG_OS WITH (NOLOCK)#(lf)#(lf)        WHERE #(lf)            LOG_OS.vl_os = ORDEM_SERVICO.cd_os#(lf)            AND LOG_OS.cd_status = 3 #(lf)        ORDER BY#(lf)            LOG_OS.dt_log_os DESC#(lf)    )                                               AS dt_em_atendimento#(lf)    ,(#(lf)        SELECT TOP 1#(lf)            dt_log_os#(lf)        FROM#(lf)            LOG_OS WITH (NOLOCK)#(lf)#(lf)        WHERE #(lf)            LOG_OS.vl_os = ORDEM_SERVICO.cd_os#(lf)            AND LOG_OS.cd_status = 5 #(lf)        ORDER BY#(lf)            LOG_OS.dt_log_os DESC#(lf)    )                                               AS dt_atendimento_concluido#(lf)FROM #(lf)    CONTRATO_PRODUTO WITH (NOLOCK)#(lf)    #(lf)    INNER JOIN ORDEM_SERVICO            WITH (NOLOCK)   ON  ORDEM_SERVICO.vl_con_tec = CONTRATO_PRODUTO.cd_contrato_produto#(lf)    LEFT JOIN CIDADE                    WITH (NOLOCK)   ON  CIDADE.cd_cidade = ORDEM_SERVICO.cd_cidade#(lf)    LEFT JOIN UF                        WITH (NOLOCK)   ON  UF.cd_uf = CIDADE.cd_uf #(lf)#(lf)WHERE#(lf)    CONTRATO_PRODUTO.cd_contrato = 17321#(lf)    #(lf)"]),
				    #"Personalização Adicionada" = Table.AddColumn(Fonte, "Tempo Em Atendimento", each if [dt_em_atendimento] <> null and [dt_atendimento_concluido] <> null then [dt_atendimento_concluido]-[dt_em_atendimento] else null),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Personalização Adicionada",{{"Tempo Em Atendimento", type number}}),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Tipo Alterado", "Personalizar", each if [Tempo Em Atendimento] = null then 0 else if [Tempo Em Atendimento] <= 0.416666666666667 then 250 else if [Tempo Em Atendimento] <= 0.833333333333333 then 379.73 else if [Tempo Em Atendimento] <= 0.1666666666666667 then 506.04 else 757.88),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Coluna Condicional Adicionada",{{"Personalizar", type number}}),
				    #"Linhas Classificadas" = Table.Sort(#"Tipo Alterado1",{{"Personalizar", Order.Descending}}),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Linhas Classificadas", "Personalizar.1", each [dt_atendimento_concluido]-[dt_em_atendimento]),
				    #"Linhas Classificadas1" = Table.Sort(#"Personalização Adicionada1",{{"Personalizar.1", Order.Descending}})
				in
				    #"Linhas Classificadas1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

